config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post '/upvote', to: 'posts#upvote', as: :upvote
    post '/downvote', to: 'posts#downvote', as: :downvote
  end
  resources :comments, only: [:create, :show] do
    post '/upvote', to: 'comments#upvote', as: :upvote
    post '/downvote', to: 'comments#downvote', as: :downvote
  end
  resources :subs
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :content, :author, :post, presence: true

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post

  has_one :parent_comment,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :child_comments,
    primary_key: :id,
    foreign_key: :parent_comment_id,
    class_name: :Comment

  has_many :votes, as: :voteable, dependent: :destroy

  def upvote(voter)
    Vote.create(
      value: 1,
      user_id: voter.id,
      voteable_type: :Comment,
      voteable_id: self.id
    )
  end

  def downvote(voter)
    Vote.create(
      value: -1,
      user_id: voter.id,
      voteable_type: :Comment,
      voteable_id: self.id
    )
  end

  def vote_sum
    sum = votes.select('SUM(value) as vote_sum').order('').first.vote_sum
    sum.nil? ? 0 : sum
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    render :new
  end

  def create
    new_comment_params = comment_params.merge(
      user_id: current_user.id, post_id: params[:post_id],
      parent_comment_id: params[:parent_comment_id]
    )
    comment = Comment.new(new_comment_params)
    if comment.save
      redirect_to post_url(comment.post)
    else
      flash[:errors] = comment.errors.full_messages
      redirect_back fallback_location: subs_url
    end
  end

  def show
    @comment = Comment.find_by(id: params[:id])
    if @comment
      @comments = @comment.child_comments
      render :show
    else
      redirect_to subs_url
    end
  end

  def upvote
    comment = Comment.find_by(id: params[:comment_id])
    if comment
      comment.upvote(current_user)
      redirect_to comment_url(comment)
    else
      redirect_back fallback_location: subs_url
    end
  end

  def downvote
    comment = Comment.find_by(id: params[:comment_id])
    if comment
      comment.downvote(current_user)
      redirect_to comment_url(comment)
    else
      redirect_back fallback_location: subs_url
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/new.html.erb
<h1>Add Comment</h1>

<%= render 'errors' %>

<form action="<%= comments_url + "?post_id=#{params[:post_id]}" %>" method="post">
  <%= auth_token %>
  <label>Comment:
    <br>
    <textarea name="comment[content]" rows="5" cols="50"></textarea>
  </label>
  <br>
  <input type="submit" value="Add Comment">
</form>

app/views/comments/show.html.erb
<p>(<%= @comment.vote_sum %>) Comment by: <%= @comment.author.username %></p>
<p><%= @comment.content %></p>

<%= button_to 'Upvote', comment_upvote_url(@comment), method: :post %>
<%= button_to 'Downvote', comment_downvote_url(@comment), method: :post %>

<form action="<%= comments_url + "?post_id=#{@comment.post_id}&parent_comment_id=#{@comment.id}" %>"
      method="post">
  <%= auth_token %>
  <label>Comment:
    <br>
    <textarea name="comment[content]" rows="5" cols="50"></textarea>
  </label>
  <br>
  <input type="submit" value="Add Comment">
</form>