config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post '/upvote', to: 'posts#upvote', as: :upvote
    post '/downvote', to: 'posts#downvote', as: :downvote
  end
  resources :comments, only: [:create, :show] do
    post '/upvote', to: 'comments#upvote', as: :upvote
    post '/downvote', to: 'comments#downvote', as: :downvote
  end
  resources :subs
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :moderator, presence: true

  belongs_to :moderator,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub,
    inverse_of: :sub

  has_many :posts,
    through: :post_subs,
    source: :post

  def posts_by_vote
    posts.left_outer_joins(:votes).joins(:author)
         .group('posts.id, users.username')
         .order('SUM(votes.value) DESC')
         .select('posts.*, SUM(votes.value) as num_votes')
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :logged_in?, except: [:index, :show]

  def new
    @sub = Sub.new
    render :new
  end

  def create
    new_sub_params = sub_params.merge(user_id: current_user.id)
    sub = Sub.new(new_sub_params)
    if sub.save
      redirect_to sub_url(sub)
    else
      flash[:errors] = sub.errors.full_messages
      redirect_to new_sub_url
    end
  end

  def edit
    @sub = Sub.find_by(id: params[:id])
    if @sub && @sub.user_id == current_user.id
      render :edit
    else
      redirect_to new_sub_url
    end
  end

  def update
    @sub = Sub.find_by(id: params[:id])
    unless @sub.user_id == current_user.id
      return redirect_to subs_url
    end
    if @sub && @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    elsif @sub.nil?
      redirect_to new_sub_url
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to edit_sub_url(@sub)
    end
  end

  def index
    @subs = Sub.all
    render :index
  end

  def show
    @sub = Sub.find_by(id: params[:id])
    if @sub
      @posts = @sub.posts_by_vote
      render :show
    else
      redirect_to subs_url
    end
  end

  def destroy
    @sub = Sub.find_by(id: params[:id])
    @sub.destroy if @sub && @sub.user_id == current_user.id
    redirect_to subs_url
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/views/subs/_form.html.erb
<% action_url = action == :new ? subs_url : sub_url(sub) %>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>Title:
    <input type="text" name="sub[title]" value="<%= sub.title %>">
  </label>
  <label>Description:
    <input type="text" name="sub[description]" value="<%= sub.description %>">
  </label>
  <input type="submit" value="<%= action == :new ? "Create Sub" : "Edit Sub" %>">
</form>

app/views/subs/_sub.html.erb
<li>
  <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
</li>

app/views/subs/create.html.erb
<h1>Subs#create,</h1>
<p>Find me in app/views/subs/create,.html.erb</p>

app/views/subs/edit.html.erb
<h1>Edit sub</h1>

<%= render 'errors' %>

<%= render 'form', action: :edit, sub: @sub %>

<%= link_to 'Sub Index', subs_url %>

app/views/subs/index.html.erb
<h1>Subs</h1>
<ul>
  <%= render @subs %>
</ul>

<%= link_to 'New Post', new_post_url %>
<%= link_to 'Create Sub', new_sub_url %>

app/views/subs/new.html.erb
<h1>Create a new sub</h1>

<%= render 'errors' %>

<%= render 'form', action: :new, sub: @sub %>

<%= link_to 'Sub Index', subs_url %>

app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>
<h2>Moderator: <%= @sub.moderator.username %></h2>
<p><%= @sub.description %></p>

<% if current_user.id == @sub.user_id %>
  <%= button_to 'Delete Sub', sub_url(@sub), method: :delete %>
<% end %>

<h3>Posts:</h3>
<ul>
  <%= render @posts %>
</ul>

<%= link_to 'Edit Sub', edit_sub_url(@sub) %>
<%= link_to 'Sub Index', subs_url %>

app/views/subs/update.html.erb
<h1>Subs#update,</h1>
<p>Find me in app/views/subs/update,.html.erb</p>