config/routes.rb
Rails.application.routes.draw do
  resources :posts, except: [:index] do
    resources :comments, only: [:new]
    post '/upvote', to: 'posts#upvote', as: :upvote
    post '/downvote', to: 'posts#downvote', as: :downvote
  end
  resources :comments, only: [:create, :show] do
    post '/upvote', to: 'comments#upvote', as: :upvote
    post '/downvote', to: 'comments#downvote', as: :downvote
  end
  resources :subs
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author, presence: true
  validate :at_least_one_sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub,
    inverse_of: :post

  has_many :subs,
    through: :post_subs,
    source: :sub

  has_many :comments,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Comment

  has_many :votes, as: :voteable, dependent: :destroy

  def comments_by_parent_id
    comments_hash = Hash.new { |hash, key| hash[key] = [] }
    ordered_comments =
      comments.left_outer_joins(:votes).joins(:author)
              .group('comments.id, users.username')
              .order('SUM(votes.value) DESC')
              .select('comments.*, SUM(votes.value) as num_votes, users.username as author_name')
    ordered_comments.each do |comment|
      comments_hash[comment.parent_comment_id] << comment
    end
    comments_hash
  end

  def at_least_one_sub
    if subs.length < 1
      errors[:base] << "Post must have at least one sub"
    end
  end

  def upvote(voter)
    Vote.create(
      value: 1,
      user_id: voter.id,
      voteable_type: :Post,
      voteable_id: self.id
    )
  end

  def downvote(voter)
    Vote.create(
      value: -1,
      user_id: voter.id,
      voteable_type: :Post,
      voteable_id: self.id
    )
  end

  def vote_sum
    sum = votes.select('SUM(value) as vote_sum').order('').first.vote_sum
    sum.nil? ? 0 : sum
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in?, except: [:show]
  def new
    @post = Post.new
    render :new
  end

  def create
    new_post_params = post_params.merge(user_id: current_user.id)
    post = Post.new(new_post_params)
    if post.save
      redirect_to post_url(post)
    else
      flash[:errors] = post.errors.full_messages
      redirect_to new_post_url
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    if @post
      render :edit
    else
      redirect_to new_post_url
    end
  end

  def update
    @post = Post.find_by(id: params[:id])
    unless @post.user_id == current_user.id
      return redirect_to subs_url
    end
    if @post && @post.update_attributes(post_params)
      redirect_to post_url(@post)
    elsif @post.nil?
      redirect_to new_post_url
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to edit_post_url(@post)
    end
  end

  def show
    @post = Post.find_by(id: params[:id])
    if @post
      @all_comments = @post.comments_by_parent_id
      render :show
    else
      redirect_to subs_url
    end
  end

  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy if @post && @post.user_id == current_user.id
    redirect_to subs_url
  end

  def upvote
    post = Post.find_by(id: params[:post_id])
    if post
      post.upvote(current_user)
      redirect_to post_url(post)
    else
      redirect_back fallback_location: subs_url
    end
  end

  def downvote
    post = Post.find_by(id: params[:post_id])
    if post
      post.downvote(current_user)
      redirect_to post_url(post)
    else
      redirect_back fallback_location: subs_url
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<li>
  <span>(<%= comment.num_votes %>)</span>
  <span><%= link_to 'Comment', comment_url(comment) %> by: <%= comment.author_name %></span>
  <br>
  <span>Created at: <%= comment.created_at %></span>
  <br>
  <span><%= comment.content %></span>
  <ul>
    <% all_comments[comment.id].each do |c2| %>
      <%= render 'comment', comment: c2, all_comments: all_comments %>
    <% end %>
  </ul>
</li>

app/views/posts/_form.html.erb
<% action_url = action == :new ? posts_url : post_url(post) %>

<form action="<%= action_url %>" method="POST">
  <%= auth_token %>
  <% if action == :edit %>
    <input type="hidden" name="_method" value="PATCH">
  <% end %>
  <label>Title:
    <input type="text" name="post[title]" value="<%= post.title %>">
  </label>
  <label>URL:
    <input type="text" name="post[url]" value="<%= post.url %>">
  </label>
  <label>Content:
    <input type="text" name="post[content]" value="<%= post.content %>">
  </label>
  <br>
  <% Sub.all.each do |sub| %>
    <label><%= sub.title %>
      <input type="checkbox"
             name="post[sub_ids][]"
             value="<%= sub.id %>"
             <%= "checked" if post.sub_ids.include?(sub.id) %>>
    </label>
  <% end %>
  <br>
  <input type="submit" value="<%= action == :new ? "Create Post" : "Edit Post" %>">
</form>

app/views/posts/_post.html.erb
<li>
  <p>
    (<%= post.num_votes %>)
    <a href="<%= post_url(post) %>"><%= post.title %></a>
  <% if post.url && post.url != '' %>
    (<a href="<%= post.url %>"><%= post.url %></a>)
  <% end %>
  </p>
</li>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'errors' %>

<%= render 'form', action: :edit, post: @post %>

<%= link_to 'Sub Index', subs_url %>

app/views/posts/new.html.erb
<h1>Create a new post</h1>

<%= render 'errors' %>

<%= render 'form', action: :new, post: @post %>

<%= link_to 'Sub Index', subs_url %>

app/views/posts/show.html.erb
<h1>
  <%= @post.title %>
  <% if @post.url && @post.url != '' %>
    (<a href="<%= @post.url %>"><%= @post.url %></a>)
  <% end %>
</h1>
<h2>Author: <%= @post.author.username %></h2>

<p><%= @post.content %></p>

<%= button_to 'Upvote', post_upvote_url(@post), method: :post %>
<%= button_to 'Downvote', post_downvote_url(@post), method: :post %>

<% if current_user.id == @post.user_id %>
  <%= button_to 'Delete Post', post_url(@post), method: :delete %>
<% end %>

<br>

<%= link_to 'Add Comment', new_post_comment_url(@post) %>

<br>

<p>Comments</p>
<ul>
  <% @all_comments[nil].each do |comment| %>
      <%= render 'comment', comment: comment, all_comments: @all_comments %>
  <% end %>
</ul>

<br><br>

<%= link_to 'Edit Post', edit_post_url(@post) %>
<%= link_to 'Sub Index', subs_url %>